package lab1;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Thanh Tam
 */
public class bai11 extends javax.swing.JFrame {

    /**
     * Creates new form bai11
     */
    public bai11() {
        initComponents();
        khoitao();
    }

    public void khoitao() {
        this.setTitle("Ví dụ java 3");
        this.setLocationRelativeTo(null);
        this.setSize(600, 300);

        JLabel headerJLabel = new JLabel("Control in action checkbox",
                JLabel.CENTER);
        headerJLabel.setSize(600, 50);
        this.add(headerJLabel);

        JCheckBox chktao = new JCheckBox("Táo");
        JCheckBox chkxoai = new JCheckBox("Xoái");
        JCheckBox chkle = new JCheckBox("Lê");

        chktao.setSize(100, 50);
        chktao.setLocation(100, 50);
        this.add(chktao);

        chkxoai.setSize(100, 50);
        chkxoai.setLocation(200, 50);
        this.add(chkxoai);

        chkle.setSize(100, 50);
        chkle.setLocation(300, 50);
        this.add(chkle);

        JLabel footerLabel = new JLabel("Táo được chọn", JLabel.CENTER);
        footerLabel.setSize(this.getWidth(), 50);
        footerLabel.setLocation(0, 100);
        this.add(footerLabel);

        chktao.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                footerLabel.setText("Táo Checkbox: "
                        + (e.getStateChange() == 1 ? "checked" : "unchecked"));
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
