/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab4;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Thanh Tam
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        menuOpen = new javax.swing.JButton();
        menuSave = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtFooter = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        edPage = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenuItem();
        menuOpen2 = new javax.swing.JMenuItem();
        menuSave2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRed = new javax.swing.JRadioButtonMenuItem();
        menuGreen = new javax.swing.JRadioButtonMenuItem();
        menuBlue = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuTextcolor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        menuOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Open folder.png"))); // NOI18N
        menuOpen.setFocusable(false);
        menuOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenActionPerformed(evt);
            }
        });
        jToolBar1.add(menuOpen);

        menuSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save.png"))); // NOI18N
        menuSave.setFocusable(false);
        menuSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(menuSave);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        btnSave.setText("Save");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        txtFooter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFooter.setText("FPT POLYTECHNIC");

        jScrollPane2.setViewportView(edPage);

        jMenu1.setText("File");

        menuNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add.png"))); // NOI18N
        menuNew.setText("New");
        menuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewActionPerformed(evt);
            }
        });
        jMenu1.add(menuNew);

        menuOpen2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuOpen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Open file.png"))); // NOI18N
        menuOpen2.setText("Open");
        menuOpen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpen2ActionPerformed(evt);
            }
        });
        jMenu1.add(menuOpen2);

        menuSave2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuSave2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save.png"))); // NOI18N
        menuSave2.setText("Save");
        menuSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSave2ActionPerformed(evt);
            }
        });
        jMenu1.add(menuSave2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Color");

        buttonGroup1.add(menuRed);
        menuRed.setText("Red");
        menuRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRedActionPerformed(evt);
            }
        });
        jMenu2.add(menuRed);

        buttonGroup1.add(menuGreen);
        menuGreen.setText("Green");
        menuGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGreenActionPerformed(evt);
            }
        });
        jMenu2.add(menuGreen);

        buttonGroup1.add(menuBlue);
        menuBlue.setText("Blue");
        menuBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBlueActionPerformed(evt);
            }
        });
        jMenu2.add(menuBlue);
        jMenu2.add(jSeparator1);

        menuTextcolor.setText("Textcolor");
        menuTextcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTextcolorActionPerformed(evt);
            }
        });
        jMenu2.add(menuTextcolor);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("System");

        jMenuItem5.setText("About");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Exit");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
            .addComponent(txtFooter)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuTextcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTextcolorActionPerformed
       Color c = JColorChooser.showDialog(null, 
               "Chọn màu chữ", Color.white);
       txtFooter.setForeground(c); // Đổi màu chữ
    }//GEN-LAST:event_menuTextcolorActionPerformed

    private void menuGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGreenActionPerformed
         txtFooter.setBackground(Color.GREEN);
    }//GEN-LAST:event_menuGreenActionPerformed

   File filename;
    
    private void menuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenActionPerformed
       JFileChooser file =new JFileChooser();
        int result = file.showOpenDialog(null);
        if(result==0) // 0: ok, 1: cancel/exit
        {
            try {
                filename= file.getSelectedFile(); //Lưu file vào bộ nhớ cục bộ
                edPage.setPage("file:///"+filename.getPath());
            } catch (IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_menuOpenActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        JFileChooser file =new JFileChooser();
        int result = file.showSaveDialog(null);
        if(result==0) // 0: ok, 1: cancel/exit
        {
                File filename = file.getSelectedFile();
            try {
              
                PrintWriter pw = new PrintWriter(filename);
                pw.println(edPage.getText());
                pw.close();
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
                
        }

    }//GEN-LAST:event_menuSaveActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
     
        PrintWriter pw;
        try {
            pw = new PrintWriter(filename);
            pw.println(edPage.getText());
            pw.close();
            JOptionPane.showMessageDialog(this, "Lưu lại thành công");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
              
    }//GEN-LAST:event_btnSaveActionPerformed

    private void menuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewActionPerformed
       edPage.setText("");
       filename = null;
    }//GEN-LAST:event_menuNewActionPerformed

    private void menuOpen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpen2ActionPerformed
       menuOpenActionPerformed(evt);
    }//GEN-LAST:event_menuOpen2ActionPerformed

    private void menuSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSave2ActionPerformed
      btnSaveActionPerformed(evt);
    }//GEN-LAST:event_menuSave2ActionPerformed

    private void menuRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRedActionPerformed
        txtFooter.setBackground(Color.red);
    }//GEN-LAST:event_menuRedActionPerformed

    private void menuBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBlueActionPerformed
       txtFooter.setBackground(Color.BLUE);
    }//GEN-LAST:event_menuBlueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JEditorPane edPage;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JRadioButtonMenuItem menuBlue;
    private javax.swing.JRadioButtonMenuItem menuGreen;
    private javax.swing.JMenuItem menuNew;
    private javax.swing.JButton menuOpen;
    private javax.swing.JMenuItem menuOpen2;
    private javax.swing.JRadioButtonMenuItem menuRed;
    private javax.swing.JButton menuSave;
    private javax.swing.JMenuItem menuSave2;
    private javax.swing.JMenuItem menuTextcolor;
    private javax.swing.JTextField txtFooter;
    // End of variables declaration//GEN-END:variables
}
